spring:
  datasource:
    url: "jdbc:h2:mem:ddhf_data;MODE=MARIADB"
    driverClassName: org.h2.Driver
    username: sa
    password: ""
# jpa:
#   show-sql: true
  liquibase:
    contexts: createdjangodb,test

  test:
    database:
      replace: none
#
#   databasePlatform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
#     path: /h2-console
#     settings.trace: false
#     settings.web-allow-others: false

